/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * MediSync - Healthcare Resource Scheduling API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppointmentInput,
  AppointmentSummary,
  AppointmentWithDoctor,
  Doctor,
  DoctorInput,
  ErrorResponse,
  HealthStatus
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListDoctorsUrl = () => {




  return `/api/doctors`
}

/**
 * Returns a list of all available doctors
 * @summary List all doctors
 */
export const listDoctors = async ( options?: RequestInit): Promise<Doctor[]> => {

  return customFetch<Doctor[]>(getListDoctorsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDoctorsQueryKey = () => {
    return [
    `/api/doctors`
    ] as const;
    }


export const getListDoctorsQueryOptions = <TData = Awaited<ReturnType<typeof listDoctors>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDoctors>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDoctorsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDoctors>>> = ({ signal }) => listDoctors({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDoctors>>, TError, TData> & { queryKey: QueryKey }
}

export type ListDoctorsQueryResult = NonNullable<Awaited<ReturnType<typeof listDoctors>>>
export type ListDoctorsQueryError = ErrorType<unknown>


/**
 * @summary List all doctors
 */

export function useListDoctors<TData = Awaited<ReturnType<typeof listDoctors>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDoctors>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListDoctorsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateDoctorUrl = () => {




  return `/api/doctors`
}

/**
 * @summary Create a doctor
 */
export const createDoctor = async (doctorInput: DoctorInput, options?: RequestInit): Promise<Doctor> => {

  return customFetch<Doctor>(getCreateDoctorUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(doctorInput)
  }
);}




export const getCreateDoctorMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDoctor>>, TError,{data: BodyType<DoctorInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createDoctor>>, TError,{data: BodyType<DoctorInput>}, TContext> => {

const mutationKey = ['createDoctor'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDoctor>>, {data: BodyType<DoctorInput>}> = (props) => {
          const {data} = props ?? {};

          return  createDoctor(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDoctorMutationResult = NonNullable<Awaited<ReturnType<typeof createDoctor>>>
    export type CreateDoctorMutationBody = BodyType<DoctorInput>
    export type CreateDoctorMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create a doctor
 */
export const useCreateDoctor = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDoctor>>, TError,{data: BodyType<DoctorInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createDoctor>>,
        TError,
        {data: BodyType<DoctorInput>},
        TContext
      > => {
      return useMutation(getCreateDoctorMutationOptions(options));
    }

export const getListAppointmentsUrl = () => {




  return `/api/appointments`
}

/**
 * Returns upcoming appointments with doctor details
 * @summary List upcoming appointments
 */
export const listAppointments = async ( options?: RequestInit): Promise<AppointmentWithDoctor[]> => {

  return customFetch<AppointmentWithDoctor[]>(getListAppointmentsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAppointmentsQueryKey = () => {
    return [
    `/api/appointments`
    ] as const;
    }


export const getListAppointmentsQueryOptions = <TData = Awaited<ReturnType<typeof listAppointments>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAppointments>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAppointmentsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAppointments>>> = ({ signal }) => listAppointments({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAppointments>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAppointmentsQueryResult = NonNullable<Awaited<ReturnType<typeof listAppointments>>>
export type ListAppointmentsQueryError = ErrorType<unknown>


/**
 * @summary List upcoming appointments
 */

export function useListAppointments<TData = Awaited<ReturnType<typeof listAppointments>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAppointments>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListAppointmentsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateAppointmentUrl = () => {




  return `/api/appointments`
}

/**
 * Books an appointment. Returns 409 if the doctor is already booked at the requested time.
 * @summary Book an appointment
 */
export const createAppointment = async (appointmentInput: AppointmentInput, options?: RequestInit): Promise<AppointmentWithDoctor> => {

  return customFetch<AppointmentWithDoctor>(getCreateAppointmentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(appointmentInput)
  }
);}




export const getCreateAppointmentMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAppointment>>, TError,{data: BodyType<AppointmentInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createAppointment>>, TError,{data: BodyType<AppointmentInput>}, TContext> => {

const mutationKey = ['createAppointment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAppointment>>, {data: BodyType<AppointmentInput>}> = (props) => {
          const {data} = props ?? {};

          return  createAppointment(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAppointmentMutationResult = NonNullable<Awaited<ReturnType<typeof createAppointment>>>
    export type CreateAppointmentMutationBody = BodyType<AppointmentInput>
    export type CreateAppointmentMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Book an appointment
 */
export const useCreateAppointment = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAppointment>>, TError,{data: BodyType<AppointmentInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createAppointment>>,
        TError,
        {data: BodyType<AppointmentInput>},
        TContext
      > => {
      return useMutation(getCreateAppointmentMutationOptions(options));
    }

export const getDeleteAppointmentUrl = (id: number,) => {




  return `/api/appointments/${id}`
}

/**
 * @summary Cancel an appointment
 */
export const deleteAppointment = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteAppointmentUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAppointmentMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAppointment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAppointment>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteAppointment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAppointment>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAppointment(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAppointmentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAppointment>>>

    export type DeleteAppointmentMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Cancel an appointment
 */
export const useDeleteAppointment = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAppointment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAppointment>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteAppointmentMutationOptions(options));
    }

export const getGetAppointmentSummaryUrl = () => {




  return `/api/appointments/summary`
}

/**
 * Returns counts by doctor and upcoming vs past
 * @summary Get appointment summary stats
 */
export const getAppointmentSummary = async ( options?: RequestInit): Promise<AppointmentSummary> => {

  return customFetch<AppointmentSummary>(getGetAppointmentSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAppointmentSummaryQueryKey = () => {
    return [
    `/api/appointments/summary`
    ] as const;
    }


export const getGetAppointmentSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getAppointmentSummary>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAppointmentSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAppointmentSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAppointmentSummary>>> = ({ signal }) => getAppointmentSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAppointmentSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAppointmentSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getAppointmentSummary>>>
export type GetAppointmentSummaryQueryError = ErrorType<unknown>


/**
 * @summary Get appointment summary stats
 */

export function useGetAppointmentSummary<TData = Awaited<ReturnType<typeof getAppointmentSummary>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAppointmentSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAppointmentSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







