/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * MediSync - Healthcare Resource Scheduling API
 * OpenAPI spec version: 0.1.0
 */
import type { DoctorAppointmentCount } from './doctorAppointmentCount';

export interface AppointmentSummary {
  total: number;
  upcoming: number;
  past: number;
  byDoctor: DoctorAppointmentCount[];
}
